apiVersion: v1
kind: PersistentVolume
metadata:
  name: interview-manager-database
  labels:
    app: interview-manager
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /root/interview-manager-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - outlineservertoronto
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: interview-manager-database
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app: interview-manager