kind: Deployment
apiVersion: apps/v1
metadata:
  name: interview-manager-back
  labels:
    app: interview-manager-back

spec:
  #replicas: 2
  selector:
    matchLabels:
      app: interview-manager-back
  template:
    metadata:
      labels:
        app: interview-manager-back
    spec:
      containers:
        - name: interview-manager-back
          image: registry-starfallmc.danya02.ru/interview-manager/back:v1
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: interview-manager-secrets
                  key: discord_token
          volumeMounts:
            - name: db-volume
              mountPath: /data
            - name: config
              mountPath: "/config"
              readOnly: true
            - name: secrets
              mountPath: "/secrets"
              readOnly: true

      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: interview-manager-database
        - name: config
          configMap:
            name: interview-manager-discord-config
        - name: secrets
          secret:
            secretName: interview-manager-secrets


---